language: ruby
rvm:
- 2.3.1

install:
- bundle install

script: jekyll build

branches:
  only:
  - jekyll

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: jekyll