language: ruby
rvm:
- 2.3.1

install: gem install jekyll jekyll-paginate html-proofer
script: jekyll build && htmlproofer ./_site

branches:
  only:
  - jekyll

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
