# Site settings
title: Frank's Blog at GitHub
email: franklin@flinhong.com
author: Frank Lin

description: This blog is an exploration of my quirky thoughts and random adventures through life. I hope you enjoy reading and perusing my posts, please leave me a comment... I'd love to hear from you!

# Base url
url: "https://flinhong.github.io"
myurl: "https://flinhong.com"

# Pre-processing

markdown: kramdown
# highlighter: pygments
highlighter: rouge
kramdown:
  input:          GFM
  auto_ids:       true
  auto_id_prefix: 'headid-'
safe: false
permalink: /:categories/:title/
# permalink: none
lsi: false # Lexical analysis (true) takes longer for higher quality

# Where things are
source:       .
destination:  ./public
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
include:      [".htaccess"]
exclude:      ["vendor", "node_modules", "gulpfile.js", "package.json", "frank's blog-b557e339fbea.json"]
keep_files:   [".git", ".svn"]
encoding:     "UTF-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Lists
# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
paginate: 7       # Applies to blog page for pagination
# Pagination path › Important for blog page in /blog/ to work
paginate_path: "/blog/page:num/"
timezone: Asia/Chongqing

# Plugins
whitelist: []
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-minifier

feed:
  path: feed.xml

message: Like this theme? Fork it!
messageurl: https://github.com/flinhong/flinhong.github.io/tree/jekyll
# covers: true
deploy: true
reading: 东方历史评论（第1辑）
readingurl: https://book.douban.com/subject/24307937/
