name: Jekyll site CI

on:
  push:
    branches: [ jekyll ]
  pull_request:
    branches: [ jekyll ]
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
    - name: Ruby gem cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    
    - name: Build Jekyll site
      run: JEKYLL_ENV=production bundle exec jekyll build

    - name: Commit files
      run: |
        cd ./_site
        git init
        git config --local user.name "z2care"
        git config --local user.email "z2care@gmail.com"
        git add .
        git commit -m "jekyll build at $(date)"

    - name: Run with dest path
      uses: helaili/jekyll-action@v2
      with:
        target_branch: master
        token: ${{ secrets.GITHUB_TOKEN }}
